name: Hello, world!!

on: 
  workflow_dispatch
  
jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: print hello message
        run: echo "Hellow, GitHub Actions!!"  

      - name: print GHA run count
        run: |
          echo "count: ${{ github.run_number }}"