name: massai mara park 01 multiple jobs

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Grant execute permission
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: application-jar
          path: build/libs/*.jar

  deploy:
    runs-on: ubuntu-22.04
    needs: build
    steps:
      - name: Download JAR artifact
        uses: actions/download-artifact@v4
        with:
          name: application-jar
          path: .

      - name: check downloaded files
        run: ls -al

      - name: Run Spring Boot application
        run: |
          java -jar ./massai_mara_park-0.0.1-SNAPSHOT.jar &
          sleep 60

  test:
    runs-on: ubuntu-22.04
    needs: deploy
    steps:
      - name: Test Endpoint #1
        run: curl --fail http://localhost:8080

      - name: Test Endpoint #2
        run: curl --fail http://localhost:8080/images

      - name: Test Endpoint #3
        run: curl --fail http://localhost:8080/animal
