name: massai mara park 01 single job test

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Grant execute permission
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: application-jar
          path: build/libs/*.jar

  deploy_and_test:
    runs-on: ubuntu-22.04
    needs: build
    steps:
      - name: Download JAR artifact
        uses: actions/download-artifact@v4
        with:
          name: application-jar
          path: .

      - name: Rename jar
        run: mv ./*.jar app.jar

      - name: Run Spring Boot and test
        run: |
          nohup java -jar app.jar > app.log 2>&1 &
          echo "Waiting for Spring Boot to start..."

          # 30초간 포트 8080이 열릴 때까지 대기
          for i in {1..30}; do
            if curl -s http://localhost:8080 > /dev/null; then
              echo "Server is up!"
              break
            fi
            echo "Waiting..."
            sleep 2
          done

          echo "=== Application Logs ==="
          cat app.log

          echo "Running API tests..."
          curl --fail http://localhost:8080
          curl --fail http://localhost:8080/images
          curl --fail http://localhost:8080/animal
