name: massai mara park 01 deploy ec2

on:
  workflow_dispatch

env:
  EC2_HOSTNAME: "43.200.254.122"
  EC2_USER_NAME: "ubuntu"

jobs:
  build_jar:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Grant execute permission
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: application-jar
          path: build/libs/*.jar

  deploy_ec2:
    needs: build_jar
    runs-on: ubuntu-22.04

    steps:
      - name: Setup SSH Directory
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh

      - name: Make private key file
        run: |
          echo "${{ secrets.EC2_PRIVATEKEY }}" > ~/.ssh/ec2_key
          chmod 600 ~/.ssh/ec2_key

      - name: Download JAR artifact
        uses: actions/download-artifact@v4
        with:
          name: application-jar

      - name: Upload JAR to EC2 via SCP
        run: |
          JAR_FILE=$(ls *.jar | head -n 1)

          echo "Uploading $JAR_FILE to EC2..."

          scp -i ~/.ssh/ec2_key -o StrictHostKeyChecking=no \
          -o "UserKnownHostsFile=/dev/null" \
          -P 22 "$JAR_FILE" \
          ${{ env.EC2_USER_NAME }}@${{ env.EC2_HOSTNAME }}:~/

      - name: Test SSH connection
        run: |
          echo "SSH 연결 테스트 시작..."

          ssh -o StrictHostKeyChecking=no \
          -o "UserKnownHostsFile=/dev/null" \
          -i ~/.ssh/ec2_key -p 22 \
          ${{ env.EC2_USER_NAME }}@${{ env.EC2_HOSTNAME }} '
          
            nohap java -jar ./massai_mara_park-0.0.1-SNAPSHOT.jar \
            > app.log 2>&1 < /dec/null &

          '

      - name: Cleanup private key
        if: always()
        run: |
          rm -f ~/.ssh/ec2_key
